baseURL = "https://www.juanorozco.com"

title = "Juan Orozco"
languageCode = "en-us"
defaultContentLanguage = "en-us"

theme = "axiom-2"

canonifyURLs = false
rssLimit = 100
enableEmoji = true
summaryLength = 40
enableRobotsTXT = true
pluralizelisttitles = false
footnoteReturnLinkContents = "&#8617;"
pagination.pagerSize = 5

disableKinds = ["taxonomy"]

[params]
mainSections = ["post", "docs", "photography"]
copyrightYear = 2025
search = true

[params.services]
# analyticsId = "UA-DEV"
# adwordsId = "AW-DEV"
# adsenseId = "CA-PUB-DEV"
# adsenseAdSlotId = "ID-DEV"
# adwordsConversionId = "ID-DEV"
# adwordsConversionValue = 0
# facebookApp = "FB-DEV"
# facebookPixel = "FB-DEV"
# disqusUser = "na"

[params.path]
image = ""
video = "video/"
author = "images/author/"
brand = "images/brand/"
font = "font/"
pdf = "pdf/"

[params.cdn]
provider = "cloudinary"
type = "image"

[params.cloudinary]
host = "https://res.cloudinary.com/deo07tbou/"
version = ""
image = "image/upload/"
raw = "raw/upload/"
video = "video/upload/"

[params.cloudinary.presets]
base = "f_auto,q_auto/"
page = "dpr_auto,c_limit,h_800,f_auto,q_auto:best,w_800/"
feature = "w_auto,dpr_auto,c_scale,f_auto,q_auto/"
summary = "w_auto,dpr_auto,c_scale,f_auto,q_auto/"

[params.img]
width = "2048"
height = "1024"
default = "page-default.webp"

[params.font]
type = ""
files = []

[params.brand]
domain = "juanorozco.com"
email = "hi@Juanorozco.com"
faviconIco = "favicon.ico"
faviconAlt = "favicon.png"
icon1To1 = "icon-1-1.png"
icon2To1 = "icon-2-1.png"
logo = "<p style=\"text-align: center;\">JO</p>"

[outputs]
home = ["HTML", "ATOM"]
section = ["HTML"]
taxonomy = ["HTML"]

[outputFormats]
[outputFormats.ATOM]
name = "ATOM"
baseName = "feed"
mediaType = "application/atom+xml"

[mediaTypes]
[mediaTypes."application/atom+xml"]
suffixes = ["atom"]

[markup]
[markup.goldmark]
[markup.goldmark.extensions]
definitionList = false
footnote = true
linkify = false
strikethrough = false
table = true
taskList = false
typographer = false
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.parser]
attribute = false
autoHeadingID = true
[markup.highlight]
codeFences = false
noClasses = false
tabWidth = 2

[menu]
[[menu.main]]
url = "/blog/"
name = "Blog"
weight = 30
[[menu.main]]
url = "/now/"
name = "Now"
weight = 20
[[menu.main]]
url = "/docs/"
name = "Docs"
weight = 40
[[menu.main]]
url = "/photography/"
name = "Photography"
weight = 50

[[menu.mobile]]
url = "/blog/"
name = "Archive"
weight = 1

[[menu.mobile]]
url = "/now/"
name = "Now"
weight = 2

[[menu.foot]]
url = "/blog/"
name = "Blog"
weight = 1

[[menu.foot]]
url = "/now/"
name = "Now"
weight = 2

[languages]
[languages."en-us"]
weight = 1
languageName = "US English"
